// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZshV-lmsp0TXh5lvb81zuJ0qxhB_shrI',
    appId: '1:1038663547355:web:64703de4e3897323f88ffe',
    messagingSenderId: '1038663547355',
    projectId: 'fleet-ae5f8',
    authDomain: 'fleet-ae5f8.firebaseapp.com',
    storageBucket: 'fleet-ae5f8.firebasestorage.app',
    measurementId: 'G-GYFXL6EGEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFktsPgRWrKuSNXbjVJtuke240au66lnY',
    appId: '1:1038663547355:android:f38e7d3145eb1a89f88ffe',
    messagingSenderId: '1038663547355',
    projectId: 'fleet-ae5f8',
    storageBucket: 'fleet-ae5f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMQIMI7fg0wTdItCFAoFipgttpTZCZOGE',
    appId: '1:1038663547355:ios:673535a2a6066cf5f88ffe',
    messagingSenderId: '1038663547355',
    projectId: 'fleet-ae5f8',
    storageBucket: 'fleet-ae5f8.firebasestorage.app',
    iosBundleId: 'com.example.fleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMQIMI7fg0wTdItCFAoFipgttpTZCZOGE',
    appId: '1:1038663547355:ios:673535a2a6066cf5f88ffe',
    messagingSenderId: '1038663547355',
    projectId: 'fleet-ae5f8',
    storageBucket: 'fleet-ae5f8.firebasestorage.app',
    iosBundleId: 'com.example.fleet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZshV-lmsp0TXh5lvb81zuJ0qxhB_shrI',
    appId: '1:1038663547355:web:85c0fe793efe6b3bf88ffe',
    messagingSenderId: '1038663547355',
    projectId: 'fleet-ae5f8',
    authDomain: 'fleet-ae5f8.firebaseapp.com',
    storageBucket: 'fleet-ae5f8.firebasestorage.app',
    measurementId: 'G-1JDFQFWXPR',
  );

}