// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFjCnK0p7Vva26l_X1JhpGjYiAnxarbE',
    appId: '1:369631794564:web:3263dd5791967e80f339d1',
    messagingSenderId: '369631794564',
    projectId: 'fleet-eed8c',
    authDomain: 'fleet-eed8c.firebaseapp.com',
    storageBucket: 'fleet-eed8c.firebasestorage.app',
    measurementId: 'G-LZP6CS33Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIqHbgAaMY3sQHCCTtTjmJHsbPpvRBHBc',
    appId: '1:369631794564:android:c1ed81fb96fad320f339d1',
    messagingSenderId: '369631794564',
    projectId: 'fleet-eed8c',
    storageBucket: 'fleet-eed8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgiEkEuHSjEG4ysoRNDX9qB1IoPp3u7ds',
    appId: '1:369631794564:ios:c45437aaa145db21f339d1',
    messagingSenderId: '369631794564',
    projectId: 'fleet-eed8c',
    storageBucket: 'fleet-eed8c.firebasestorage.app',
    iosBundleId: 'com.example.fleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgiEkEuHSjEG4ysoRNDX9qB1IoPp3u7ds',
    appId: '1:369631794564:ios:c45437aaa145db21f339d1',
    messagingSenderId: '369631794564',
    projectId: 'fleet-eed8c',
    storageBucket: 'fleet-eed8c.firebasestorage.app',
    iosBundleId: 'com.example.fleet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHFjCnK0p7Vva26l_X1JhpGjYiAnxarbE',
    appId: '1:369631794564:web:6886d719b89d425bf339d1',
    messagingSenderId: '369631794564',
    projectId: 'fleet-eed8c',
    authDomain: 'fleet-eed8c.firebaseapp.com',
    storageBucket: 'fleet-eed8c.firebasestorage.app',
    measurementId: 'G-1QGXP58529',
  );
}
